<a href="https://colab.research.google.com/github/priyanshgupta1998/Machine_learning/blob/master/keras_vggmodel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Mount the drive in the google colab 

import zipfile
from google.colab import drive

drive.mount('/content/drive/')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:
## import libaries
import pandas as pd
import numpy as np
import cv2
import os, sys
from tqdm import tqdm

In [3]:
## load data
train = pd.read_csv('/content/drive/My Drive/DATASETS/Image_classification_hacker_earth_challenge/train.csv')
print(train.shape)
train.head()

(3215, 2)


image_id    label
0  train_1a     rice
1  train_1b    candy
2  train_1c      jam
3  train_1d   coffee
4  train_2a  vinegar

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3215 entries, 0 to 3214
Data columns (total 2 columns):
image_id    3215 non-null object
label       3215 non-null object
dtypes: object(2)
memory usage: 50.3+ KB


In [5]:
test = pd.read_csv('/content/drive/My Drive/DATASETS/Image_classification_hacker_earth_challenge/test.csv')
print(test.shape)
test.head()

(1732, 1)


image_id
0  test_1000a
1  test_1000b
2  test_1000c
3  test_1000d
4  test_1001a

In [0]:
# function to read image
def read_img(img_path):
    img = cv2.imread(img_path, cv2.IMREAD_COLOR)
    img = cv2.resize(img, (256,256))
    return img

In [0]:
## set path for images
TRAIN_PATH = '/home/train_img/'
TEST_PATH = '/home/test_img/'

In [0]:

# FOR TRAIN DATASET 
zip_ref = zipfile.ZipFile("/content/drive/My Drive/DATASETS/Image_classification_hacker_earth_challenge/train_img.zip", 'r')
zip_ref.extractall("/home")
zip_ref.close()

In [0]:

# FOR TRAIN DATASET 
zip_ref = zipfile.ZipFile("/content/drive/My Drive/DATASETS/Image_classification_hacker_earth_challenge/test_img.zip", 'r')
zip_ref.extractall("/home")
zip_ref.close()

In [10]:
train['image_id'].values

array(['train_1a', 'train_1b', 'train_1c', ..., 'train_804a',
       'train_804b', 'train_804c'], dtype=object)

In [12]:
# load data
train_img, test_img = [],[]
for img_path in tqdm(train['image_id'].values):
    train_img.append(read_img(TRAIN_PATH + img_path + '.png'))

100%|██████████| 3215/3215 [00:07<00:00, 448.44it/s]


In [17]:
print(len(train_img))               #TOTAL NO. OF IMAGES IN TRAINING INAGE
print(train_img[0].shape)           # SIZE OF ONE INDIVIDUAL IMAGE 
train_img[0]                        # ARRAY OF IMAGE ONE

3215
(256, 256, 3)


array([[[ 85,  68, 182],
        [ 90,  68, 184],
        [ 90,  73, 186],
        ...,
        [ 37,  38,  36],
        [ 34,  34,  32],
        [ 38,  35,  34]],

       [[ 90,  72, 187],
        [ 91,  72, 186],
        [ 91,  75, 187],
        ...,
        [ 36,  34,  34],
        [ 39,  35,  35],
        [ 41,  36,  36]],

       [[ 88,  72, 188],
        [ 90,  73, 188],
        [ 91,  73, 186],
        ...,
        [ 37,  32,  35],
        [ 42,  35,  38],
        [ 40,  33,  35]],

       ...,

       [[197, 203, 219],
        [193, 199, 214],
        [186, 191, 208],
        ...,
        [ 64,  89, 102],
        [ 78, 100, 113],
        [ 84, 107, 119]],

       [[197, 202, 217],
        [190, 196, 211],
        [184, 187, 205],
        ...,
        [ 63,  88, 103],
        [ 72,  95, 111],
        [ 78, 101, 117]],

       [[194, 199, 214],
        [188, 193, 207],
        [171, 171, 189],
        ...,
        [ 63,  90, 106],
        [ 74,  97, 113],
        [ 74,  97, 114]]

In [11]:
test['image_id'].values

array(['test_1000a', 'test_1000b', 'test_1000c', ..., 'test_1432b',
       'test_1432c', 'test_1432d'], dtype=object)

In [18]:
for img_path in tqdm(test['image_id'].values):
    test_img.append(read_img(TEST_PATH + img_path + '.png'))

100%|██████████| 1732/1732 [00:03<00:00, 446.49it/s]


In [19]:
print(len(test_img))               # TOTAL NO. OF IMAGES IN TESTING INAGE
print(test_img[0].shape)           # SIZE OF ONE INDIVIDUAL IMAGE 
test_img[0]                        # ARRAY OF IMAGE ONE

1732
(256, 256, 3)


array([[[ 89, 217, 239],
        [ 95, 216, 237],
        [ 81, 215, 237],
        ...,
        [191, 208, 217],
        [192, 208, 216],
        [191, 206, 215]],

       [[ 83, 217, 240],
        [ 80, 218, 241],
        [ 81, 217, 239],
        ...,
        [193, 211, 221],
        [193, 211, 220],
        [193, 211, 220]],

       [[ 82, 217, 240],
        [ 82, 218, 241],
        [ 82, 219, 241],
        ...,
        [187, 208, 219],
        [189, 210, 220],
        [195, 212, 222]],

       ...,

       [[178, 183, 198],
        [176, 181, 196],
        [173, 178, 192],
        ...,
        [ 61,  60, 140],
        [ 63,  59, 137],
        [ 58,  55, 130]],

       [[180, 185, 200],
        [176, 184, 197],
        [175, 182, 195],
        ...,
        [ 58,  60, 140],
        [ 58,  56, 135],
        [ 59,  56, 133]],

       [[179, 184, 199],
        [178, 186, 201],
        [178, 185, 199],
        ...,
        [ 56,  60, 140],
        [ 59,  57, 137],
        [ 56,  53, 131]]

In [0]:
# normalize images
x_train = np.array(train_img, np.float32) / 255.
x_test = np.array(test_img, np.float32) / 255.

In [22]:
print(x_train.shape)
x_train[0]

(3215, 256, 256, 3)


array([[[0.33333334, 0.26666668, 0.7137255 ],
        [0.3529412 , 0.26666668, 0.72156864],
        [0.3529412 , 0.28627452, 0.7294118 ],
        ...,
        [0.14509805, 0.14901961, 0.14117648],
        [0.13333334, 0.13333334, 0.1254902 ],
        [0.14901961, 0.13725491, 0.13333334]],

       [[0.3529412 , 0.28235295, 0.73333335],
        [0.35686275, 0.28235295, 0.7294118 ],
        [0.35686275, 0.29411766, 0.73333335],
        ...,
        [0.14117648, 0.13333334, 0.13333334],
        [0.15294118, 0.13725491, 0.13725491],
        [0.16078432, 0.14117648, 0.14117648]],

       [[0.34509805, 0.28235295, 0.7372549 ],
        [0.3529412 , 0.28627452, 0.7372549 ],
        [0.35686275, 0.28627452, 0.7294118 ],
        ...,
        [0.14509805, 0.1254902 , 0.13725491],
        [0.16470589, 0.13725491, 0.14901961],
        [0.15686275, 0.12941177, 0.13725491]],

       ...,

       [[0.77254903, 0.79607844, 0.85882354],
        [0.75686276, 0.78039217, 0.8392157 ],
        [0.7294118 , 0

In [23]:
print(x_test.shape)
x_test[0]

(1732, 256, 256, 3)


array([[[0.34901962, 0.8509804 , 0.9372549 ],
        [0.37254903, 0.84705883, 0.92941177],
        [0.31764707, 0.84313726, 0.92941177],
        ...,
        [0.7490196 , 0.8156863 , 0.8509804 ],
        [0.7529412 , 0.8156863 , 0.84705883],
        [0.7490196 , 0.80784315, 0.84313726]],

       [[0.3254902 , 0.8509804 , 0.9411765 ],
        [0.3137255 , 0.85490197, 0.94509804],
        [0.31764707, 0.8509804 , 0.9372549 ],
        ...,
        [0.75686276, 0.827451  , 0.8666667 ],
        [0.75686276, 0.827451  , 0.8627451 ],
        [0.75686276, 0.827451  , 0.8627451 ]],

       [[0.32156864, 0.8509804 , 0.9411765 ],
        [0.32156864, 0.85490197, 0.94509804],
        [0.32156864, 0.85882354, 0.94509804],
        ...,
        [0.73333335, 0.8156863 , 0.85882354],
        [0.7411765 , 0.8235294 , 0.8627451 ],
        [0.7647059 , 0.83137256, 0.87058824]],

       ...,

       [[0.69803923, 0.7176471 , 0.7764706 ],
        [0.6901961 , 0.70980394, 0.76862746],
        [0.6784314 , 0

In [25]:
label_list = train['label'].tolist()
label_list[:5]

['rice', 'candy', 'jam', 'coffee', 'vinegar']

In [26]:
for v,k in enumerate(set(label_list)):
    print(v , k)

0 tomatosauce
1 rice
2 jam
3 milk
4 water
5 soda
6 pasta
7 nuts
8 chocolate
9 tea
10 fish
11 chips
12 honey
13 vinegar
14 flour
15 cereal
16 beans
17 cake
18 corn
19 oil
20 sugar
21 spices
22 coffee
23 candy
24 juice


In [27]:
# target variable - encoding numeric value

Y_train = {k:v+1 for v,k in enumerate(set(label_list))}
Y_train

{'beans': 17,
 'cake': 18,
 'candy': 24,
 'cereal': 16,
 'chips': 12,
 'chocolate': 9,
 'coffee': 23,
 'corn': 19,
 'fish': 11,
 'flour': 15,
 'honey': 13,
 'jam': 3,
 'juice': 25,
 'milk': 4,
 'nuts': 8,
 'oil': 20,
 'pasta': 7,
 'rice': 2,
 'soda': 6,
 'spices': 22,
 'sugar': 21,
 'tea': 10,
 'tomatosauce': 1,
 'vinegar': 14,
 'water': 5}

In [33]:
y_train = [Y_train[k] for k in label_list]
print(y_train)

[2, 24, 3, 23, 14, 9, 21, 5, 25, 24, 25, 25, 24, 4, 23, 2, 9, 6, 25, 8, 12, 22, 16, 12, 4, 16, 24, 9, 17, 18, 2, 16, 8, 25, 23, 22, 3, 13, 25, 2, 23, 9, 4, 14, 15, 7, 24, 16, 12, 16, 25, 13, 1, 2, 24, 1, 10, 24, 9, 3, 5, 23, 10, 3, 14, 10, 16, 15, 2, 9, 15, 24, 19, 6, 23, 13, 23, 14, 3, 23, 10, 23, 9, 18, 4, 13, 20, 11, 8, 11, 12, 25, 8, 24, 19, 16, 15, 17, 9, 16, 20, 19, 6, 23, 12, 14, 10, 18, 25, 1, 24, 2, 22, 1, 19, 5, 24, 16, 4, 6, 5, 16, 12, 9, 9, 16, 4, 5, 13, 3, 9, 11, 19, 1, 6, 4, 16, 9, 17, 2, 9, 16, 24, 8, 13, 9, 10, 6, 4, 21, 13, 1, 16, 24, 9, 18, 24, 23, 24, 2, 25, 1, 1, 22, 11, 6, 10, 23, 5, 2, 9, 9, 6, 8, 2, 25, 9, 11, 24, 24, 16, 24, 9, 12, 17, 12, 9, 24, 8, 7, 2, 20, 23, 1, 2, 24, 13, 5, 8, 4, 2, 3, 13, 9, 2, 1, 8, 14, 23, 18, 3, 18, 25, 7, 10, 21, 23, 13, 2, 13, 12, 25, 10, 23, 8, 22, 19, 23, 4, 16, 19, 18, 6, 9, 5, 13, 11, 6, 24, 6, 24, 17, 14, 9, 16, 18, 23, 21, 25, 23, 19, 24, 2, 24, 4, 14, 2, 19, 22, 14, 23, 17, 10, 21, 6, 24, 25, 15, 10, 4, 24, 22, 3, 8, 16, 24, 2

In [34]:
y_train = np.array(y_train)     # list to array
y_train

array([ 2, 24,  3, ...,  8, 24, 23])

#Tensorflow - keras

In [35]:

from keras import applications
from keras.models import Model
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras.metrics import categorical_accuracy
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint

Using TensorFlow backend.


In [0]:
y_train = to_categorical(y_train)

In [37]:
#Transfer learning with Inception V3 
base_model = applications.VGG16(weights='imagenet', include_top=False, input_shape=(256, 256, 3))

Instructions for updating:
Colocations handled automatically by placer.
58892288/58889256 [==============================] - 1s 0us/step


In [42]:
print(base_model)
base_model.output_shape

(None, 8, 8, 512)

In [44]:
base_model.input

<tf.Tensor 'input_1:0' shape=(?, 256, 256, 3) dtype=float32>

In [43]:
base_model.output

<tf.Tensor 'block5_pool/MaxPool:0' shape=(?, 8, 8, 512) dtype=float32>

In [38]:
## set model architechture 
add_model = Sequential()
add_model.add(Flatten(input_shape=base_model.output_shape[1:]))

add_model.add(Dense(256, activation='relu'))       # hidden layer

add_model.add(Dense(y_train.shape[1], activation='softmax'))   #final layer 

model = Model(inputs=base_model.input, outputs=add_model(base_model.output))

model.compile(loss='categorical_crossentropy', optimizer=optimizers.SGD(lr=1e-4, momentum=0.9),metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 256, 256, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 256, 256, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 256, 256, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 128, 128, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 128, 128, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 128, 128, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 64, 64, 128)       0         
__________

In [0]:
batch_size = 32 # tune it
epochs = 5 # increase it

train_datagen = ImageDataGenerator(rotation_range=30, 
                                    width_shift_range=0.1,
                                    height_shift_range=0.1, 
                                    horizontal_flip=True)
train_datagen.fit(x_train)

In [46]:
history = model.fit_generator(
    train_datagen.flow(x_train, y_train, batch_size=batch_size),
    steps_per_epoch=x_train.shape[0] // batch_size,
    epochs=epochs,
    callbacks=[ModelCheckpoint('VGG16-transferlearning.model', monitor='val_acc', save_best_only=True)]
)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
100/100 [==============================] - 64s 643ms/step - loss: 3.1253 - acc: 0.1147
Epoch 2/5


/usr/local/lib/python3.6/dist-packages/keras/callbacks.py:434: RuntimeWarning: Can save best model only with val_acc available, skipping.
  'skipping.' % (self.monitor), RuntimeWarning)


100/100 [==============================] - 58s 578ms/step - loss: 2.6565 - acc: 0.2399
Epoch 3/5
100/100 [==============================] - 55s 553ms/step - loss: 2.1351 - acc: 0.3692
Epoch 4/5
100/100 [==============================] - 56s 561ms/step - loss: 1.7439 - acc: 0.4762
Epoch 5/5
100/100 [==============================] - 57s 568ms/step - loss: 1.5126 - acc: 0.5461


In [0]:
## predict test data
predictions = model.predict(x_test)

In [48]:
predictions

array([[7.3754090e-06, 4.0775109e-03, 3.0974038e-03, ..., 3.2736966e-04,
        5.3304690e-01, 2.7033860e-02],
       [1.7749027e-05, 1.4530937e-01, 7.8847762e-03, ..., 1.9548709e-02,
        3.3004437e-02, 1.3912750e-02],
       [2.6473833e-06, 5.3327536e-04, 4.4101478e-05, ..., 7.3449418e-04,
        5.9206246e-05, 1.1266309e-03],
       ...,
       [4.7611707e-06, 7.5286604e-04, 1.9089067e-02, ..., 5.1384527e-02,
        1.1131955e-02, 3.4632692e-03],
       [1.2830648e-05, 2.0226769e-02, 1.4411493e-02, ..., 1.0449480e-01,
        3.3360901e-03, 8.2023250e-04],
       [1.3684812e-04, 2.3905775e-01, 6.4317882e-03, ..., 5.3343702e-02,
        1.2364411e-03, 8.3878050e-03]], dtype=float32)

In [49]:
Y_train.items()

dict_items([('tomatosauce', 1), ('rice', 2), ('jam', 3), ('milk', 4), ('water', 5), ('soda', 6), ('pasta', 7), ('nuts', 8), ('chocolate', 9), ('tea', 10), ('fish', 11), ('chips', 12), ('honey', 13), ('vinegar', 14), ('flour', 15), ('cereal', 16), ('beans', 17), ('cake', 18), ('corn', 19), ('oil', 20), ('sugar', 21), ('spices', 22), ('coffee', 23), ('candy', 24), ('juice', 25)])

In [0]:
# get labels
predictions = np.argmax(predictions, axis=1)
rev_y = {v:k for k,v in Y_train.items()}
pred_labels = [rev_y[k] for k in predictions]

In [53]:
pred_labels[:5]

['candy', 'honey', 'vinegar', 'water', 'candy']

In [54]:
## make submission
sub = pd.DataFrame({'image_id':test.image_id, 'label':pred_labels})
sub.head()

image_id    label
0  test_1000a    candy
1  test_1000b    honey
2  test_1000c  vinegar
3  test_1000d    water
4  test_1001a    candy

In [0]:
sub.to_csv('/home/sub_vgg.csv', index=False) ## ~0.59