<a href="https://colab.research.google.com/github/priyanshgupta1998/Machine_learning/blob/master/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
cd /home

/home


In [2]:

from xlrd import open_workbook
import csv
wb = open_workbook('problem_statement.xlsx')
for i in range(wb.nsheets):
    sheet = wb.sheet_by_index(i)
    print(sheet.name)
    with open("%s.csv" %(sheet.name.replace(" ","")), "w") as file:
        writer = csv.writer(file, delimiter = ",")
        print(sheet, sheet.name, sheet.ncols, sheet.nrows)
        header = [cell.value for cell in sheet.row(0)]
        writer.writerow(header)
        for row_idx in range(1, sheet.nrows):
            row = [int(cell.value) if isinstance(cell.value, float) else cell.value
                   for cell in sheet.row(row_idx)]
            writer.writerow(row)

Problem Statement
<xlrd.sheet.Sheet object at 0x7f53bf939588> Problem Statement 1 25
Credit_card_fraud_linear_1
<xlrd.sheet.Sheet object at 0x7f53bf9395c0> Credit_card_fraud_linear_1 8 2663
Credit_card_fraud (2)
<xlrd.sheet.Sheet object at 0x7f53bf9395f8> Credit_card_fraud (2) 18 2663
Credit_card_fraud_linear_2
<xlrd.sheet.Sheet object at 0x7f53bf939630> Credit_card_fraud_linear_2 8 2663
Credit_card_fraud_linear_3
<xlrd.sheet.Sheet object at 0x7f53bf939668> Credit_card_fraud_linear_3 8 2663
Credit_card_fraud_linear_4
<xlrd.sheet.Sheet object at 0x7f53bf9396a0> Credit_card_fraud_linear_4 8 2663
Credit_card_fraud_linear_5
<xlrd.sheet.Sheet object at 0x7f53bf9396d8> Credit_card_fraud_linear_5 8 2663
Credit_card_fraud_linear_6
<xlrd.sheet.Sheet object at 0x7f53bf939710> Credit_card_fraud_linear_6 8 2663


In [0]:
import pandas as pd
import numpy as np

#Now take 5th data for training purpose

In [102]:
df = pd.read_csv('Credit_card_fraud_linear_5.csv')
print(df.shape)
df.head(10)

(2662, 8)


Customer_Type  $_Spent_per_day  ...  Year  $_Surcharge_Levied
0         Coral               59  ...  2019                 -35
1         Coral               37  ...  2017                 -22
2         Coral              158  ...  2019                 -10
3         Coral               50  ...  2017                 -62
4         Coral               50  ...  2019                 -22
5         Coral              130  ...  2018                 -57
6         Coral              136  ...  2018                 -22
7         Coral              130  ...  2017                 -53
8         Coral              191  ...  2019                 -46
9         Coral               45  ...  2018                 -47

[10 rows x 8 columns]

In [5]:
df.describe()

$_Spent_per_day  ...  $_Surcharge_Levied
count      2662.000000  ...         2662.000000
mean        338.233283  ...          -29.872652
std         238.113807  ...           24.909787
min           2.000000  ...         -182.000000
25%         159.000000  ...          -46.000000
50%         289.000000  ...          -29.000000
75%         455.000000  ...          -12.000000
max        1237.000000  ...           31.000000

[8 rows x 7 columns]

In [0]:
list(df['$_Surcharge_Levied'])

In [6]:
df.isnull().sum()

Customer_Type                0
$_Spent_per_day              0
#_of_transactions_per_day    0
$_credited_per_day           0
Day                          0
Month                        0
Year                         0
$_Surcharge_Levied           0
dtype: int64

In [7]:
df['Customer_Type'].unique()

array(['Coral', 'Diamond', 'Family', 'Ruby', 'Sapphire'], dtype=object)

In [8]:
pd.get_dummies(df['Customer_Type']).head()

Coral  Diamond  Family  Ruby  Sapphire
0      1        0       0     0         0
1      1        0       0     0         0
2      1        0       0     0         0
3      1        0       0     0         0
4      1        0       0     0         0

In [9]:
df = pd.get_dummies(df, columns=['Customer_Type'])
df.head()

$_Spent_per_day  ...  Customer_Type_Sapphire
0               59  ...                       0
1               37  ...                       0
2              158  ...                       0
3               50  ...                       0
4               50  ...                       0

[5 rows x 12 columns]

In [10]:
print(df.shape)
print(df.ndim)  

(2662, 12)
2


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2662 entries, 0 to 2661
Data columns (total 12 columns):
$_Spent_per_day              2662 non-null int64
#_of_transactions_per_day    2662 non-null int64
$_credited_per_day           2662 non-null int64
Day                          2662 non-null int64
Month                        2662 non-null int64
Year                         2662 non-null int64
$_Surcharge_Levied           2662 non-null int64
Customer_Type_Coral          2662 non-null uint8
Customer_Type_Diamond        2662 non-null uint8
Customer_Type_Family         2662 non-null uint8
Customer_Type_Ruby           2662 non-null uint8
Customer_Type_Sapphire       2662 non-null uint8
dtypes: int64(7), uint8(5)
memory usage: 158.7 KB


In [12]:
X  = df.drop('$_Surcharge_Levied', axis=1)
print(X.shape)
X.head()

(2662, 11)


$_Spent_per_day  ...  Customer_Type_Sapphire
0               59  ...                       0
1               37  ...                       0
2              158  ...                       0
3               50  ...                       0
4               50  ...                       0

[5 rows x 11 columns]

In [13]:
Y = df['$_Surcharge_Levied']
print(Y.shape)
Y.head()

(2662,)


0   -35
1   -22
2   -10
3   -62
4   -22
Name: $_Surcharge_Levied, dtype: int64

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [56]:

from sklearn import preprocessing
y_train_norm = preprocessing.normalize(np.array(y_train).reshape(-1, 1))
y_train_norm[:10]

array([[-1.],
       [ 1.],
       [-1.],
       ...,
       [-1.],
       [-1.],
       [-1.]])

In [52]:

from sklearn import preprocessing
y_norm = preprocessing.normalize(np.array(y_test).reshape(-1, 1))
y_norm[:10]

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [0]:
import os
import pandas as pd
from pandas import DataFrame,Series
from sklearn import tree
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.preprocessing import StandardScaler
import statsmodels.formula.api as smf
import statsmodels.api as sm
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
from sklearn import neighbors
from sklearn import linear_model
%matplotlib inline

In [90]:
dec = tree.DecisionTreeRegressor(max_depth=1)
dec.fit(X_train, y_train)


DecisionTreeRegressor(criterion='mse', max_depth=1, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

**although the smaller the RMSE, the better result/accuracy**




In [91]:
from sklearn import metrics 
dec_pred = dec.predict(X_test)
print(metrics.mean_squared_error(y_test , dec_pred))
print(metrics.r2_score(y_test , dec_pred))

321.8177174538784
0.51195413376089


In [89]:
# fit a model
lm = linear_model.LinearRegression()
li = lm.fit(X_train, y_train)
li_pred = li.predict(X_test)
print(metrics.mean_squared_error(y_test , li_pred))

10.123911228117391


In [84]:
from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor()
reg.fit(X_train,y_train)
ran_pred = reg.predict(X_test)
print(metrics.mean_squared_error(y_test , ran_pred))

16.741615472127418


/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [88]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1, max_depth = 5, alpha = 10, n_estimators = 10)
xg_reg.fit(X_train,y_train)
xgb_preds = xg_reg.predict(X_test)
print(metrics.mean_squared_error(y_test , xgb_preds))

[14:22:16] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
569.8759932584971


/usr/local/lib/python3.6/dist-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


In [32]:
from xlrd import open_workbook
import csv
wb = open_workbook('Prediction_data.xlsx')
for i in range(wb.nsheets):
    sheet = wb.sheet_by_index(i)
    print(sheet.name)
    with open("%s.csv" %(sheet.name.replace(" ","")), "w") as file:
        writer = csv.writer(file, delimiter = ",")
        print(sheet, sheet.name, sheet.ncols, sheet.nrows)
        header = [cell.value for cell in sheet.row(0)]
        writer.writerow(header)
        for row_idx in range(1, sheet.nrows):
            row = [int(cell.value) if isinstance(cell.value, float) else cell.value
                   for cell in sheet.row(row_idx)]
            writer.writerow(row)

Prediction_Data
<xlrd.sheet.Sheet object at 0x7f5398a84da0> Prediction_Data 8 271
Credit_card_fraud (2)
<xlrd.sheet.Sheet object at 0x7f5398a84dd8> Credit_card_fraud (2) 18 2663


In [80]:
test_df = pd.read_csv('Prediction_Data.csv')
print(test_df.shape)
test_df.head(10)

(270, 8)


Customer_Type  $_Spent_per_day  ...  Year  $_Surcharge_Levied
0         Coral               75  ...  2019                 NaN
1         Coral               38  ...  2019                 NaN
2         Coral              139  ...  2019                 NaN
3         Coral               46  ...  2019                 NaN
4         Coral               43  ...  2019                 NaN
5         Coral              113  ...  2019                 NaN
6         Coral              123  ...  2019                 NaN
7         Coral              132  ...  2019                 NaN
8         Coral              158  ...  2019                 NaN
9         Coral               25  ...  2019                 NaN

[10 rows x 8 columns]

In [35]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 8 columns):
Customer_Type                270 non-null object
$_Spent_per_day              270 non-null int64
#_of_transactions_per_day    270 non-null int64
$_credited_per_day           270 non-null int64
Day                          270 non-null int64
Month                        270 non-null int64
Year                         270 non-null int64
$_Surcharge_Levied           0 non-null float64
dtypes: float64(1), int64(6), object(1)
memory usage: 17.0+ KB


In [36]:
test_df = pd.get_dummies(test_df, columns=['Customer_Type'])
test_df.head()

$_Spent_per_day  ...  Customer_Type_Sapphire
0               75  ...                       0
1               38  ...                       0
2              139  ...                       0
3               46  ...                       0
4               43  ...                       0

[5 rows x 12 columns]

In [37]:
print(test_df.shape)

(270, 12)


In [38]:
X_dftest  = test_df.drop('$_Surcharge_Levied', axis=1)
print(X_dftest.shape)
X_dftest.head()

(270, 11)


$_Spent_per_day  ...  Customer_Type_Sapphire
0               75  ...                       0
1               38  ...                       0
2              139  ...                       0
3               46  ...                       0
4               43  ...                       0

[5 rows x 11 columns]

In [66]:

from sklearn import preprocessing
y_out = preprocessing.normalize(np.array(Y).reshape(-1, 1))
y_out[:10]

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

**E+01 means moving the decimal point one digit to the right, E+00 means leaving the decimal point where it is, and E–01 means moving the decimal point one digit to the left.**

In [0]:
print(Output.shape)
Output

In [0]:
leived_val = list(output)

In [0]:
# dec_out , random_out, output, Output

In [108]:
new = pd.DataFrame(list(Output))
new.describe()


0
count  270.000000
mean     0.344815
std      0.749592
min     -1.000000
25%     -0.175000
50%      0.700000
75%      1.000000
max      1.000000

In [107]:
mean = 0.344815
std = 0.749592
n= []
for i in list(Output):
  n.append(((i-mean)/std)*100)
new['1'] = n
new.head(10)

0           1
0 -0.9 -166.065673
1  0.5   20.702596
2 -0.2  -72.681539
3 -0.9 -166.065673
4  0.5   20.702596
5 -1.0 -179.406264
6 -0.2  -72.681539
7  0.8   60.724367
8  0.2  -19.319176
9  0.4    7.362005

In [81]:
leived_val = list(output)
test_df['$_Surcharge_Levied'] = leived_val
print(test_df.shape)
test_df.head(10)
test_df.to_csv('prediction_output.csv' , index = False)

(270, 8)


Customer_Type  $_Spent_per_day  ...  Year  $_Surcharge_Levied
0         Coral               75  ...  2019           -4.694708
1         Coral               38  ...  2019           -0.044147
2         Coral              139  ...  2019            2.027745
3         Coral               46  ...  2019           -4.673445
4         Coral               43  ...  2019           -0.381894
5         Coral              113  ...  2019           -6.082844
6         Coral              123  ...  2019            0.480528
7         Coral              132  ...  2019            3.962320
8         Coral              158  ...  2019            1.439361
9         Coral               25  ...  2019            1.958150

[10 rows x 8 columns]