<a href="https://colab.research.google.com/github/priyanshgupta1998/Machine_learning/blob/master/Sample_Skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INSAID Hiring Exercise

## Important: Kindly go through the instructions mentioned below.

- The Sheet is structured in **4 steps**:
    1. Understanding data and manipulation
    2. Data visualization
    3. Implementing Machine Learning models(Note: It should be more than 1 algorithm)
    4. Model Evaluation and concluding with the best of the model.
    
    
    

- Try to break the codes in the **simplest form** and use number of code block with **proper comments** to them
- We are providing **h** different dataset to choose from(Note: You need to select any one of the dataset from this sample sheet only)
- The **interview calls** will be made solely based on how good you apply the **concepts**.
- Good Luck! Happy Coding!

#Load data file from local system

In [2]:
import os
from google.colab import files
files.upload()
print(os.listdir())

Saving Churn.csv to Churn.csv
['.config', 'Churn.csv', 'sample_data']


# Importing the data

In [3]:
# use these links to do so:
#Importing the essential libraries
import pandas as pd
import numpy as np
data = pd.read_csv('Churn.csv')
print(data.shape)
data.head()

(7043, 21)


customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

`We have 7048 rows and 21 columns in he given dataset`

`churn variable signifying whether the customer had left the company two months after observation`

#Analyse the whole data

### Understanding the data

In [25]:
#make a copy of the dataset
df = data.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
dtypes: float64(1), int64(2), obj

`We have only three columns which have numbers But others have Obejcts like string.`

In [4]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

`We can clearly see we don't have any null cell or block`

In [37]:
df.describe()

SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

`We don't see here that much level of difference (no outliers) , Everthing is perfect`

### Data Manipulation

#Let's explore categorical data

In [36]:
df['gender'].value_counts()

Male      3555
Female    3488
Name: gender, dtype: int64

In [7]:
df['Partner'].value_counts()

No     3641
Yes    3402
Name: Partner, dtype: int64

In [8]:
df['Dependents'].value_counts()

No     4933
Yes    2110
Name: Dependents, dtype: int64

In [9]:
df['PhoneService'].value_counts()

Yes    6361
No      682
Name: PhoneService, dtype: int64

In [10]:
df['MultipleLines'].value_counts()

No                  3390
Yes                 2971
No phone service     682
Name: MultipleLines, dtype: int64

In [11]:
df['InternetService'].value_counts()

Fiber optic    3096
DSL            2421
No             1526
Name: InternetService, dtype: int64

In [12]:
df['OnlineSecurity'].value_counts()

No                     3498
Yes                    2019
No internet service    1526
Name: OnlineSecurity, dtype: int64

In [13]:
df['OnlineBackup'].value_counts()

No                     3088
Yes                    2429
No internet service    1526
Name: OnlineBackup, dtype: int64

In [14]:
df['DeviceProtection'].value_counts()

No                     3095
Yes                    2422
No internet service    1526
Name: DeviceProtection, dtype: int64

In [15]:
df['TechSupport'].value_counts()

No                     3473
Yes                    2044
No internet service    1526
Name: TechSupport, dtype: int64

In [16]:
df['StreamingTV'].value_counts()

No                     2810
Yes                    2707
No internet service    1526
Name: StreamingTV, dtype: int64

In [17]:
df['StreamingMovies'].value_counts()

No                     2785
Yes                    2732
No internet service    1526
Name: StreamingMovies, dtype: int64

In [18]:
df['Contract'].value_counts()

Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

In [19]:
df['PaperlessBilling'].value_counts()

Yes    4171
No     2872
Name: PaperlessBilling, dtype: int64

In [20]:
df['PaymentMethod'].value_counts()

Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: PaymentMethod, dtype: int64

`after analyse whole data we are seeing that we will have more 26 columns in our current dataset after creating dummy variables.`

#Let's create dummmy variables  for 15 columns

In [0]:
import pandas as pd
df1 = pd.get_dummies(df['gender'])
df2 = pd.get_dummies(df['Partner'])
df3 = pd.get_dummies(df['Dependents'])
df4 = pd.get_dummies(df['PhoneService'])
df5 = pd.get_dummies(df['MultipleLines'])
df6 = pd.get_dummies(df['InternetService'])
df7 = pd.get_dummies(df['OnlineSecurity'])
df8 = pd.get_dummies(df['OnlineBackup'])
df9 = pd.get_dummies(df['DeviceProtection'])
df10 = pd.get_dummies(df['TechSupport'])
df11 = pd.get_dummies(df['StreamingTV'])
df12 = pd.get_dummies(df['StreamingMovies'])
df13 = pd.get_dummies(df['Contract'])
df14 = pd.get_dummies(df['PaperlessBilling'])
df15 = pd.get_dummies(df['PaymentMethod'])


In [0]:
#Let's drop all the extra columns from the dataset ,, below is the list
liis = ['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod']  

df.drop(liis , axis =1 , inplace=True)

In [28]:
print(df.shape)
df.head()

(7043, 6)


customerID  SeniorCitizen  tenure  MonthlyCharges TotalCharges Churn
0  7590-VHVEG              0       1           29.85        29.85    No
1  5575-GNVDE              0      34           56.95       1889.5    No
2  3668-QPYBK              0       2           53.85       108.15   Yes
3  7795-CFOCW              0      45           42.30      1840.75    No
4  9237-HQITU              0       2           70.70       151.65   Yes

In [29]:
df_new = pd.concat([df, df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15], axis=1)
print(df_new.shape)
df_new.head()

(7043, 47)


customerID  SeniorCitizen  ...  Electronic check  Mailed check
0  7590-VHVEG              0  ...                 1             0
1  5575-GNVDE              0  ...                 0             1
2  3668-QPYBK              0  ...                 0             1
3  7795-CFOCW              0  ...                 0             0
4  9237-HQITU              0  ...                 1             0

[5 rows x 47 columns]

`Here  customer Id is not making any sense to dataset , so just remove it .`

In [0]:
df_new.drop('customerID',axis=1 , inplace=True)

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_new['Churn'] = le.fit_transform(df_new['Churn'])
print(df['Churn'].unique())

['No' 'Yes']


In [32]:
df_new['Churn'].value_counts()

0    5174
1    1869
Name: Churn, dtype: int64

In [45]:
#convert object(srting ) to int ot float
lisss = []
k= list(df_new['TotalCharges'])
for i in range(len(k)):
  if(k[i]!=' '):
    lisss.append(float(k[i]))
#     print(i, k[i] , float(k[i]))
  else:
    lisss.append(0.0)
#     print(0)

#   
  
print(len(lisss))
lisss[:6]

7043


[29.85, 1889.5, 108.15, 1840.75, 151.65, 820.5]

In [0]:
df_new['TotalCharges'] = lisss

In [0]:
df_new.info()

#Let's split our data into predictor and target column.

In [48]:
X = df_new.drop('Churn' , axis =1)
y = df_new['Churn']

print(X.shape)
print(y.shape)

(7043, 45)
(7043,)


In [49]:

# b = np.array(y)
# b = b.reshape(-1,1)
# print(b.shape)


y = y.values.reshape(-1,1)
print(y.shape)


(7043, 1)


#it's time to split our dataset into training and validation set

` “calibration” database consisting of 4000 customers and a “validation” database consisting of 3043 customers`

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=3043, random_state=42)

In [51]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4000, 45)
(3043, 45)
(4000, 1)
(3043, 1)


In [0]:
X_train.info()

In [53]:
y_train

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]])

### Implement Machine Learning Models

#Here we need to apply classification model to classify chunk column

In [0]:
from sklearn.metrics import accuracy_score
#importing all the required ML packages
from sklearn.linear_model import LogisticRegression #logistic regression
from sklearn import svm #support vector Machine
from sklearn.ensemble import RandomForestClassifier #Random Forest
from sklearn.neighbors import KNeighborsClassifier #KNN
from sklearn.naive_bayes import GaussianNB #Naive bayes
from sklearn.tree import DecisionTreeClassifier #Decision Tree
from sklearn import metrics #accuracy measure

#1.)Logistic Regresion

In [67]:
# Logistic Regression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [56]:
y_pred[:10]

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [68]:
#Check validation accuracy of model on validaiton dataset
from sklearn.metrics import accuracy_score
lscore =accuracy_score(y_test,y_pred)
print('The accuracy of the Logistic Regression is', lscore)

#test the validation dataset on model
score_logreg = logreg.score(X_test,y_test)
score_logreg

The accuracy of the Logistic Regression is 0.8136707196845219


0.8136707196845219

#2.)linear SVM for binary classificaiton

In [69]:
# Support Vector Classifier (SVM/SVC)
from sklearn.svm import SVC
svc = SVC(gamma=0.22)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
y_pred[:10]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [70]:
#Check validation accuracy of model on validaiton dataset
from sklearn.metrics import accuracy_score
sscore =accuracy_score(y_test,y_pred)
print('The accuracy of the SVM is', sscore)

#on validation dataset
score_svc = svc.score(X_test,y_test)
print('The accuracy of SVC is', score_svc)

The accuracy of the SVM is 0.7564903056194545
The accuracy of SVC is 0.7564903056194545


#3.)Apply decision Tree

In [71]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred[:10]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [72]:
#Check validation accuracy of model on validaiton dataset
from sklearn.metrics import accuracy_score
dscore =accuracy_score(y_test,y_pred)
print('The accuracy of the decesion tree is', dscore)

#on validation dataset
score_svc = clf.score(X_test,y_test)
print('The accuracy of  decesion tree is', score_svc)

The accuracy of the decesion tree is 0.7400591521524811
The accuracy of  decesion tree is 0.7400591521524811


#Model Evaluation

#### As we can see the accuracy of the various models that we've choose for binary classification

In [78]:
print('The accuracy of the Logistic Regression is', str(round(lscore*100)) + '%')
print('The accuracy of the SVM is',str(round(sscore*100)) + '%')
print('The accuracy of the decesion tree is', str(round(dscore*100)) + '%')

The accuracy of the Logistic Regression is 81.0%
The accuracy of the SVM is 76.0%
The accuracy of the decesion tree is 74.0%


#Final Conclusion

`We are getting more accuracy in case of Logistic Regression , so we have it as a good model and use for further process.`